### PR TITLE
Update Build Module.py

### PR DESCRIPTION
**Pull request by purushothaman-p**
Changed the code in such a way that it opens the defined webpage in incognito mode rather than normal mode.

### CODE REVIEW

**Comment by M4SK3D** [comment]
Could the mode be an option?

**Comment by M4SK3D** [comment]
Like a check box?

**Comment by purushothaman-p** [comment]
Yes. That could be an additional advantage.

**Comment by M4SK3D** [comment]
so why don't you add a check box button?:-D

**Review by M4SK3D — CHANGES_REQUESTED** [review]
The code indeed works. For now, till further update, let this sit in this branch. After the checkbox is implemented, commit to this branch. Then a merge can be made as Mark IV

**Review by M4SK3D — APPROVED** [review]

**Pull request merged**
